---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
  - name: update repos
    apt:
      update_cache: yes
    changed_when: False
  - include_tasks: tasks/flatpak_remote_repo.yml

  tasks:
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/snap_installs.yml
    - include_tasks: tasks/flatpak_installs.yml